### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [Alsham0/SVC#1]
Muy bien, jóvenes. Me gustó su diseño simple y elegante.

Les adjunto algunas correcciones para que apliquen:
- Falta el ícono de Alonso.
- Añadan en una parte un párrafo inventado sobre la historia de su empresa.
- Quiten el separador que aparece debajo del logo de su empresa.

Espero su respuesta.

**Comment by AngelVe11** [comment]
Gracias profesor.
Ya realizamos las correcciones que nos comento.

**Comment by CarlosRubioTNM** [comment]
Excelente, jóvenes. Gracias por su trabajo. Cierro el Issue.
